### PR TITLE
Add justl-per-recipe-buffer custom variable

### LINKED ISSUE #44: Create a buffer per command
Hello, would it be possible to add the command name to the `*just*` buffer so that we can run multiple long running commands in parallel?

For example, given a `ghcid` and `format` command, just.el would create one buffer per command:
- `*just-ghcid*`
- `*just-format*`

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Fixes #44

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Running the tests with and without the custom seem to work, though I am not sure how to test the setting actually work, e.g. can we set the custom for the duration of a given test?

Also the `:sentinel` arg does not seem to be used and since this change the api I think we should remove it.

**Comment by psibi** [comment]
@TristanCacqueray LGTM overall. 

> can we set the custom for the duration of a given test?

Not sure. But can you write a test such that you do `customize-set-variable` and then run a recipe and check that the new buffer is actually created ? And then at the end reset using `customize-set-variable` to the original value so that it doesn't affect other test.

Also, if you manually test to check that TRAMP integration is not broken using the following steps: https://github.com/psibi/justl.el/tree/master/test ? Alternatively, I can do that at the end before merging this.

One more thing: If you can update the changelog and README with an explanation of this `defcustom`, that will be helpful also.

> Also the :sentinel arg does not seem to be used and since this change the api I think we should remove it.

As long as the test passes and the TRAMP integration doesn't break, go for it. :-)

**Comment by TristanCacqueray** [comment]
@psibi Thanks for the prompt review and the suggestions. I have validated that this change works over TRAMP, but using ssh instead of docker (because my emacs is already running in a container :).

**Comment by psibi** [comment]
Thank you!

**Pull request merged**
